version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: inithub-postgres
    environment:
      POSTGRES_DB: inithub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"